import = ["~/.config/alacritty/catppuccin-mocha.toml"]

[env]
TERM = "xterm-256color"

[font]
size = 25

[font.normal]
family = "JetBrainsMono Nerd Font"

[window]
decorations = "none"

[window.padding]
x = 7
y = 0
