#!/bin/bash

# A setup script for my configuration

# Meant to be run on every new machine i use / work on in order to have all of my 
# essential tools quickly and out of the box (should work on WSL and macOS)

# brew packages mac
# amethyst alacritty neovim fzf bash-completion@2 tmux mactex exa

# ubuntu packages apt
# ripgrep gh

# ubuntu apt neovim setup
# neovim gcc g++ unzip

# create directories
export XDG_CONFIG_HOME="$HOME/.config"
mkdir -p "$XDG_CONFIG_HOME"/bash

# symbolic links
ln -sf "$PWD/alacritty" "$XDG_CONFIG_HOME/alacritty"
ln -sf "$PWD/bash/.bash_profile" "$HOME/.bash_profile"
ln -sf "$PWD/bash/.bashrc" "$HOME/.bashrc"
ln -sf "$PWD/tmux/.tmux.conf" "$HOME/.tmux.conf"

# check for os system
unameOut="$(uname -s)"
case "${unameOut}" in
    Linux*)     machine=Linux;;
    Darwin*)    machine=Mac;;
    CYGWIN*)    machine=Cygwin;;
    MINGW*)     machine=MinGw;;
    *)          machine="UNKNOWN:${unameOut}"
esac

# nvim configuration

if [ "$machine" == "Mac" ]; then
    ln -sf "$PWD/nvim_macos" "$XDG_CONFIG_HOME/nvim"      
elif [ "$(expr substr $(uname -s) 1 5)" == "Linux" ]; then
    ln -sf "$PWD/nvim_linux" "$XDG_CONFIG_HOME/nvim"
fi
