#!/bin/zsh

# A setup script for my configuration

# Meant to be run on every new machine i use / work on in order to have all of my
# essential tools quickly and out of the box (should work on WSL/Linux and macOS)
# For Linux, the assumed distro is Arch (or at least, having pacman as a PM)
#!/bin/zsh

CONFIGS=("emacs" "git" "kitty" "lazygit" "nvim" "openvpn" "starship.toml" "tmux" "yazi" "zathura" "zsh")
CONFIGS_LINUX=("dunstrc" "hypr" "waybar" "wofi" "rofi")
CONFIGS_MACOS=("aerospace")
PACKAGES=("git" "neovim" "fzf" "tmux" "starship" "ripgrep" "gcc" "pyenv" "lsd" "lazygit")
CASKS=("google-chrome" "mactex" "sioyek" "linearmouse" "raycast" "hiddenbar" "obsidian")

command_exists() {
    command -v "$1" >/dev/null 2>&1
}

unameOut="$(uname -s)"
case "${unameOut}" in
    Linux*)     machine=Linux;;
    Darwin*)    machine=Mac;;
    *)          machine="UNKNOWN:${unameOut}"
esac

export XDG_CONFIG_HOME="$HOME/.config"
mkdir -p "$XDG_CONFIG_HOME"

echo "Creating symbolic links..."
ln -sfn "$PWD/.zshrc" "$HOME/.zshrc"
ln -sfn "$PWD/.template" "$HOME/.template"

for config in "${CONFIGS[@]}"; do
    ln -sfn "$PWD/$config" "$XDG_CONFIG_HOME/$config"
done

if [ "$machine" = "Mac" ]; then
    for config in "${CONFIGS_MACOS[@]}"; do
        ln -sfn "$PWD/$config" "$XDG_CONFIG_HOME/$config"
    done
elif [ "$machine" = "Linux" ]; then
    for config in "${CONFIGS_LINUX[@]}"; do
        ln -sfn "$PWD/$config" "$XDG_CONFIG_HOME/$config"
    done
fi

if [ ! -d "$HOME/.oh-my-zsh" ]; then
    printf "Oh My Zsh is not installed. Do you want to install it? (y/n): "
    read -r install_omz
    if [[ "$install_omz" =~ ^[Yy]$ ]]; then
        echo "Installing Oh My Zsh..."
        RUNZSH=no sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
    fi
fi

if [ "$machine" = "Mac" ]; then
    echo "Starting setup for mac..."

    if ! command_exists brew; then
        printf "Homebrew not found. Do you want to install it? (y/n): "
        read -r install_homebrew
        if [[ "$install_homebrew" =~ ^[Yy]$ ]]; then
            /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
        fi
    fi

    if command_exists brew; then
        echo "Updating/Upgrading Homebrew..."
        brew update && brew upgrade

        printf "Do you want to install homebrew formulae and casks? (y/n): "
        read -r confirm
        if [[ "$confirm" =~ ^[Yy]$ ]]; then
            for package in "${PACKAGES[@]}"; do
                brew list "$package" &>/dev/null || brew install "$package"
            done
            for cask in "${CASKS[@]}"; do
                brew list --cask "$cask" &>/dev/null || brew install --cask "$cask"
            done
        fi
        brew cleanup
    fi

elif [ "$machine" = "Linux" ]; then
    echo "Starting setup on Linux..."
    
    if ! command_exists pacman; then
        echo "Pacman not found, your distro is not compatible with this setup script."
        exit 1
    fi

    echo "Updating pacman..."
    sudo pacman -Syu --noconfirm

    printf "Do you want to install pacman packages? (y/n): "
    read -r confirm
    if [[ "$confirm" =~ ^[Yy]$ ]]; then
        for package in "${PACKAGES[@]}"; do
            pacman -Qq "$package" &>/dev/null || sudo pacman -S --noconfirm "$package"
        done
    fi
fi

